// components/icons.tsx
import {
  Moon,
  Sun,
  Laptop,
  Github,
  Linkedin,
  Mail,
  Menu,
  X,
  Download,
  Code,
  Briefcase,
  User,
  Home,
  ChevronRight,
  ExternalLink,
  Check,
  Phone,
  Trophy,
  ArrowRight,
  Star,
  Loader2,
  type LucideProps,
} from "lucide-react";

export type IconProps = LucideProps;

export const Icons = {
  logo: Check,
  sun: Sun,
  moon: Moon,
  laptop: Laptop,
  github: Github,
  linkedin: Linkedin,
  mail: Mail,
  menu: Menu,
  close: X,
  download: Download,
  code: Code,
  briefcase: Briefcase,
  user: User,
  home: Home,
  chevronRight: ChevronRight,
  externalLink: ExternalLink,
  check: Check,
  phone: Phone,
  trophy: Trophy,
  arrowRight: ArrowRight,
  star: Star,
  spinner: Loader2,
};
